FROM registry.redhat.io/ubi9@sha256:c342e86b66854269554d8ac8e53e6e34d540c2289b06e19897037cb219c5ec59 as builder

USER root

RUN dnf install -y perl gcc openssl openssl-devel cmake gcc-c++ git curl-minimal unzip cyrus-sasl-devel rust cargo

RUN mkdir /tmp/tuftool
COPY . /tmp/tuftool
RUN cd /tmp/tuftool && cargo build --release

FROM registry.access.redhat.com/ubi9/ubi:latest@sha256:8942b73866f8434571d6fc4c10cbebd48982995d2249c39302e4d71e7df3afd9 as deploy

COPY --from=builder /tmp/tuftool/target/release/tuftool /usr/bin/

ENTRYPOINT ["/usr/bin/tuftool"]

LABEL description ="Tuftool is a Rust command-line utility for generating and signing TUF repositories"
LABEL io.k8s.description="Tuftool is a Rust command-line utility for generating and signing TUF repositories"
LABEL io.k8s.display-name="Tuftool container image for Red Hat Trusted Artifact Signer"
LABEL io.openshift.tags="Tuftool Trusted Artifact Signer"
LABEL summary="Provides the Tuftool binary for generating and signing TUF repositories"
LABEL com.redhat.component="tuftool"
LABEL name="rhtas/tuftool-rhel9"

