FROM --platform=linux/amd64   quay.io/securesign/cli-tuftool@sha256:34a016f568321f31c784bae6272500bdc8ff4abfa68c251bc8a0123319bc8ca1 AS build-amd64
FROM --platform=linux/arm64   quay.io/securesign/cli-tuftool@sha256:c73a2547bf1f1214551b6140c28e13a00c6a3fd238aac14cfce80d4e4ed72332 AS build-arm64
FROM --platform=linux/ppc64le quay.io/securesign/cli-tuftool@sha256:bcf395e4a9aa5347e072ce7d8a88078607d3b833cf08975d1ff40dbfc53dcfa0 AS build-ppc64le
FROM --platform=linux/s390x   quay.io/securesign/cli-tuftool@sha256:439cca291999db75340102e859235361a1ea0d7d3b59bf2487f102b9b327590a AS build-s390x

FROM registry.redhat.io/ubi9/go-toolset:latest@sha256:9ef42b045aaabcaff14b76c75c086ec1479fbc7502c0587efdcedb2d721c46e5 AS packager
USER root
RUN mkdir -p /binaries

COPY --from=build-amd64 /usr/bin/tuftool /tmp/tuftool
RUN tar -czf /binaries/tuftool_linux_amd64.tar.gz -C /tmp tuftool && \
    rm /tmp/tuftool

COPY --from=build-arm64 /usr/bin/tuftool /tmp/tuftool
RUN tar -czf /binaries/tuftool_linux_arm64.tar.gz -C /tmp tuftool && \
    rm /tmp/tuftool

COPY --from=build-ppc64le /usr/bin/tuftool /tmp/tuftool
RUN tar -czf /binaries/tuftool_linux_ppc64le.tar.gz -C /tmp tuftool && \
    rm /tmp/tuftool

COPY --from=build-s390x /usr/bin/tuftool /tmp/tuftool
RUN tar -czf /binaries/tuftool_linux_s390x.tar.gz -C /tmp tuftool && \
    rm /tmp/tuftool

# Final minimal image with all binaries
FROM registry.redhat.io/ubi9/ubi-minimal@sha256:463cae32c6f6f5594b11a5c22de275016bd8545ce58a6373388e8b24f13fc15c

LABEL description="Flat image containing tuftool CLI binary for CDN distribution"
LABEL io.k8s.description="Flat image containing tuftool CLI binary for CDN distribution"
LABEL io.opencontainers.image.description="Flat image containing tuftool CLI binary for CDN distribution"
LABEL io.k8s.display-name="Tuftool CLI stack image for Red Hat Trusted Artifact Signer"
LABEL io.openshift.tags="tuftool trusted-artifact-signer cli-stack"
LABEL summary="Provides tuftool CLI binary as tar.gz archive for CDN distribution."
LABEL com.redhat.component="tuftool-cli-stack"

COPY --from=packager /binaries/ /binaries/
COPY licenses/LICENSE-APACHE /licenses/license.txt

RUN chown -R root:0 /binaries && chmod -R g+r /binaries

USER 65532:65532
