FROM registry.access.redhat.com/ubi9/ubi:latest as builder

USER root

RUN dnf install -y perl gcc openssl openssl-devel cmake gcc-c++ git curl-minimal unzip cyrus-sasl-devel rust cargo

RUN mkdir /tmp/tuftool
COPY . /tmp/tuftool
RUN cd /tmp/tuftool && cargo build --release

FROM registry.access.redhat.com/ubi9/ubi:latest as deploy

COPY --from=builder /tmp/tuftool/target/release/tuftool /usr/bin/

COPY rhtas/tuf-repo-init.sh /usr/bin/

ENTRYPOINT ["/usr/bin/tuf-repo-init.sh"]
USER 1001

LABEL description ="Tuffer is a utility application used for generating an initial trust root for RHTAS"
LABEL io.k8s.description="Tuffer is a utility application used for generating an initial trust root for RHTAS"
LABEL io.k8s.display-name="Tuffer container image for Red Hat Trusted Artifact Signer"
LABEL io.openshift.tags="Tuffer Trusted Artifact Signer"
LABEL summary="Provides the tuf-repo-init script for generating an initial trust root for RHTAS"
LABEL com.redhat.component="tuffer"
LABEL name="rhtas/tuffer-rhel9"
LABEL cpe="cpe:/a:redhat:trusted_artifact_signer:1.2::el9"
