FROM registry.redhat.io/ubi9/go-toolset:9.7-1773318690@sha256:2a6a828a4020b8a03875bb0fa72cf41c0bd8695c2e5c60f49acb5fcdbd1e35cf as builder
ENV CGO_ENABLED=1 \
    GOEXPERIMENT=strictfipsruntime

USER root

RUN dnf install -y perl gcc openssl openssl-devel cmake gcc-c++ git curl-minimal unzip cyrus-sasl-devel rust cargo

RUN mkdir /tmp/tuftool
COPY . /tmp/tuftool
RUN cd /tmp/tuftool && cargo build --release --features fips

FROM registry.access.redhat.com/ubi9/ubi-minimal@sha256:c9805b434e84d05a4ac392ab3df76a8740ce15df57d65801ef28e3d6c5218afb as deploy

COPY --from=builder /tmp/tuftool/target/release/tuftool /usr/bin/

ENTRYPOINT ["/usr/bin/tuftool"]

LABEL description ="Tuftool is a Rust command-line utility for generating and signing TUF repositories"
LABEL io.k8s.description="Tuftool is a Rust command-line utility for generating and signing TUF repositories"
LABEL io.k8s.display-name="Tuftool container image for Red Hat Trusted Artifact Signer"
LABEL io.openshift.tags="Tuftool Trusted Artifact Signer"
LABEL summary="Provides the Tuftool binary for generating and signing TUF repositories"
LABEL com.redhat.component="tuftool"
LABEL name="rhtas/tuftool-rhel9"
