FROM --platform=linux/amd64   quay.io/securesign/cli-tuftool@sha256:7fc5acf77acdd166f0c146edc32520b1812c5e58698d0222bd93276b6021854c AS build-amd64
FROM --platform=linux/arm64   quay.io/securesign/cli-tuftool@sha256:94e27958df8f4cdb6c3a611b37f32fbe7627e9bbacc6e09b1631ee7506429c62 AS build-arm64
FROM --platform=linux/ppc64le quay.io/securesign/cli-tuftool@sha256:7ca3614bda96d506b601bab6b432bea3152fd7eeede48afe035188f77e5c7241 AS build-ppc64le
FROM --platform=linux/s390x   quay.io/securesign/cli-tuftool@sha256:62de6ec2cad30259609dece7abb237975adf91255458fb94dddd04acdfec23b2 AS build-s390x

FROM registry.redhat.io/ubi9/go-toolset:latest@sha256:9ef42b045aaabcaff14b76c75c086ec1479fbc7502c0587efdcedb2d721c46e5 AS packager
USER root
RUN mkdir -p /binaries

COPY --from=build-amd64 /usr/bin/tuftool /tmp/tuftool
RUN tar -czf /binaries/tuftool_linux_amd64.tar.gz -C /tmp tuftool && \
    rm /tmp/tuftool

COPY --from=build-arm64 /usr/bin/tuftool /tmp/tuftool
RUN tar -czf /binaries/tuftool_linux_arm64.tar.gz -C /tmp tuftool && \
    rm /tmp/tuftool

COPY --from=build-ppc64le /usr/bin/tuftool /tmp/tuftool
RUN tar -czf /binaries/tuftool_linux_ppc64le.tar.gz -C /tmp tuftool && \
    rm /tmp/tuftool

COPY --from=build-s390x /usr/bin/tuftool /tmp/tuftool
RUN tar -czf /binaries/tuftool_linux_s390x.tar.gz -C /tmp tuftool && \
    rm /tmp/tuftool

# Final minimal image with all binaries
FROM registry.redhat.io/ubi9/ubi-minimal@sha256:463cae32c6f6f5594b11a5c22de275016bd8545ce58a6373388e8b24f13fc15c

LABEL description="Flat image containing tuftool CLI binary for CDN distribution"
LABEL io.k8s.description="Flat image containing tuftool CLI binary for CDN distribution"
LABEL io.opencontainers.image.description="Flat image containing tuftool CLI binary for CDN distribution"
LABEL io.k8s.display-name="Tuftool CLI stack image for Red Hat Trusted Artifact Signer"
LABEL io.openshift.tags="tuftool trusted-artifact-signer cli-stack"
LABEL summary="Provides tuftool CLI binary as tar.gz archive for CDN distribution."
LABEL com.redhat.component="tuftool-cli-stack"

COPY --from=packager /binaries/ /binaries/
COPY licenses/LICENSE-APACHE /licenses/license.txt

RUN chown -R root:0 /binaries && chmod -R g+r /binaries

USER 65532:65532
