FROM quay.io/securesign/cli-tuftool@sha256:96dd680be18d8d1c3eced452b9f455769fc5b94761dd72bb7cb76b1d3d19b637 AS build-amd64

FROM registry.redhat.io/ubi9/go-toolset:9.7-1778604137@sha256:e06a6f4c85c3ca75f64127542449c9770fb885adfb592f987c576d268ac108de AS packager
USER root
RUN mkdir -p /binaries

# Linux amd64 (tuftool is linux-only, single-platform)
COPY --from=build-amd64 /usr/bin/tuftool /tmp/tuftool
RUN tar -czf /binaries/tuftool_linux_amd64.tar.gz -C /tmp tuftool && \
    rm /tmp/tuftool

# Final minimal image with all binaries
FROM registry.redhat.io/ubi9/ubi-minimal@sha256:12db9874bd753eb98b1ab3d840e75de5d6842ac0604fbd68c012adefe97140be

LABEL description="Flat image containing tuftool CLI binary for CDN distribution"
LABEL io.k8s.description="Flat image containing tuftool CLI binary for CDN distribution"
LABEL io.opencontainers.image.description="Flat image containing tuftool CLI binary for CDN distribution"
LABEL io.k8s.display-name="Tuftool CLI stack image for Red Hat Trusted Artifact Signer"
LABEL io.openshift.tags="tuftool trusted-artifact-signer cli-stack"
LABEL summary="Provides tuftool CLI binary as tar.gz archive for CDN distribution."
LABEL com.redhat.component="tuftool-cli-stack"

COPY --from=packager /binaries/ /binaries/
COPY licenses/LICENSE-APACHE /licenses/license.txt

RUN chown -R root:0 /binaries && chmod -R g+r /binaries

USER 65532:65532
