FROM registry.redhat.io/ubi9/go-toolset:latest@sha256:180d433d97773ac90384662ee0f54c3b474f6eeb7219e414a4ca323d1196bb13 as builder
ENV CGO_ENABLED=1 \
    GOEXPERIMENT=strictfipsruntime

USER root

RUN dnf install -y perl gcc openssl openssl-devel cmake gcc-c++ git curl-minimal unzip cyrus-sasl-devel rust cargo

RUN mkdir /tmp/tuftool
COPY . /tmp/tuftool
RUN cd /tmp/tuftool && cargo build --release --features fips

FROM registry.access.redhat.com/ubi9/ubi:latest@sha256:edabf9436bb372addcca3537aa76111c7a1aba970f5e3b02e2e03bc72943612d as deploy

COPY --from=builder /tmp/tuftool/target/release/tuftool /usr/bin/
COPY licenses/LICENSE-APACHE /licenses/license.txt

COPY rhtas/tuf-repo-init.sh /usr/bin/

ENTRYPOINT ["/usr/bin/tuf-repo-init.sh"]
USER 65532:65532

LABEL description ="Tuffer is a utility application used for generating an initial trust root for RHTAS"
LABEL io.k8s.description="Tuffer is a utility application used for generating an initial trust root for RHTAS"
LABEL io.k8s.display-name="Tuffer container image for Red Hat Trusted Artifact Signer"
LABEL io.openshift.tags="Tuffer Trusted Artifact Signer"
LABEL summary="Provides the tuf-repo-init script for generating an initial trust root for RHTAS"
LABEL com.redhat.component="tuffer"
LABEL name="rhtas/tuffer-rhel9"
