FROM registry.redhat.io/ubi9@sha256:f09be5a4b3eed653eb88eb4d9f936823522d89947baab4aca6fadd543d857abb as builder

USER root

RUN dnf install -y perl gcc openssl openssl-devel cmake gcc-c++ git curl-minimal unzip cyrus-sasl-devel rust cargo

RUN mkdir /tmp/tuftool
COPY . /tmp/tuftool
RUN cd /tmp/tuftool && cargo build --release

FROM registry.access.redhat.com/ubi9/ubi:latest@sha256:6ed9f6f637fe731d93ec60c065dbced79273f1e0b5f512951f2c0b0baedb16ad as deploy

COPY --from=builder /tmp/tuftool/target/release/tuftool /usr/bin/

COPY rhtas/tuf-repo-init.sh /usr/bin/

ENTRYPOINT ["/usr/bin/tuf-repo-init.sh"]
USER 1001

LABEL description ="Tuffer is a utility application used for generating an initial trust root for RHTAS"
LABEL io.k8s.description="Tuffer is a utility application used for generating an initial trust root for RHTAS"
LABEL io.k8s.display-name="Tuffer container image for Red Hat Trusted Artifact Signer"
LABEL io.openshift.tags="Tuffer Trusted Artifact Signer"
LABEL summary="Provides the tuf-repo-init script for generating an initial trust root for RHTAS"
LABEL com.redhat.component="tuffer"
LABEL name="rhtas/tuffer-rhel9"
