apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/build-nudge-files: ".*.env, .*.yml, .*README.md"
    build.appstudio.openshift.io/repo: https://github.com/securesign/tough?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "release-1.4" && ( "Dockerfile.tuffer".pathChanged() || ".tekton/tuffer-push.yaml".pathChanged()
      || "deny.toml".pathChanged() || "Cargo.toml".pathChanged() || "Cargo.lock".pathChanged()
      || "tough/***".pathChanged() || "tuftool/***".pathChanged() || "Makefile".pathChanged()
      || "rhtas/***".pathChanged() || "trigger-konflux-builds.txt".pathChanged() ||
      "rpms.lock.yaml".pathChanged() || "ubi.repo".pathChanged() )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: tough-v1-4
    appstudio.openshift.io/component: tuffer-v1-4
    pipelines.appstudio.openshift.io/type: build
  name: tuffer-v1-4-on-push
  namespace: rhtas-tenant
spec:
  params:
  - name: release-version
    value: "1.4.3"
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/securesign/tuffer:{{revision}}
  - name: dockerfile
    value: Dockerfile.tuffer
  - name: build-source-image
    value: "true"
  - name: prefetch-input
    value: '[{"type": "cargo", "path": "."}, {"type": "rpm", "path": "."}]'
  - name: hermetic
    value: "true"
  - name: dev-package-managers
    value: "true"
  - name: fips-check
    value: "true"
  pipelineRef:
    params:
    - name: url
      value: https://github.com/securesign/pipelines.git
    - name: revision
      value: main
    - name: pathInRepo
      value: pipelines/docker-build-oci-ta.yaml
    resolver: git
  taskRunTemplate:
    serviceAccountName: build-pipeline-tuffer-v1-4
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
