name: Rust
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/dependabot.yml"
    branches: [develop]

env:
  # From-scratch builds with incremental compilation enabled adds unneeded performance and disk overhead.
  CARGO_INCREMENTAL: "0"
  CMAKE_GENERATOR: Ninja

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        make_target: ["check-licenses", "build", "integ", "integ-fips"]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: windows-latest
            make_target: check-licenses
          - os: macos-latest
            make_target: check-licenses
          - os: macos-latest
            make_target: integ-fips
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        with:
          path: |
            .cargo
          # you can edit the .github/cache_bust file if you need to clear the cache
          key: ${{ hashFiles('.github/cache_bust') }}-${{ runner.os }}-${{ matrix.make_target }}-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ hashFiles('.github/cache_bust') }}-${{ runner.os }}-${{ matrix.make_target }}
      - uses: ilammy/setup-nasm@72793074d3c8cdda771dba85f6deafe00623038b # v1.5.2
      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@96bed6edff20d1dd61ecff9b75cc519d516e6401 # v5
      # print the current rustc. replace stable to pin to a specific toolchain version.
      # - run: rustup default stable
      - run: rustup default 1.84.0
      - run: rustup component add rustfmt
      - run: rustup component add clippy
      - name: Install CMake 3.x (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get remove --purge --auto-remove cmake -y
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO cmake.sh https://github.com/Kitware/CMake/releases/download/v3.27.6/cmake-3.27.6-linux-x86_64.sh
          sudo mkdir -p /opt/cmake
          sudo sh cmake.sh --prefix=/opt/cmake --skip-license
          echo "/opt/cmake/bin" >> $GITHUB_PATH
      - name: Install CMake 3.x (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install cmake --version=3.27.6 -y --installargs 'ADD_CMAKE_TO_PATH=System' --allow-downgrade
        shell: powershell
      - name: Install OpenSSL (Windows)
        if: runner.os == 'Windows'
        shell: powershell
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_INSTALLATION_ROOT" | Out-File -FilePath $env:GITHUB_ENV -Append
          vcpkg install openssl:x64-windows-static-md
      - run: make ${{ matrix.make_target }}
