name: Specification version check

on:
  workflow_dispatch:  # Allows manual trigger only

jobs:
  specification-bump-check:
    permissions:
      contents: read
      issues: write
    uses: theupdateframework/specification/.github/workflows/check-latest-spec-version.yml@master
    with:
      tuf-version: "v1.0.29"
